### ISSUE TITLE
How to convert corrected data to positive values? 

### ISSUE THREAD

**Issue by RoseString** [LTLA/batchelor#37]
Dear developer,

Thank you a lot for the the great tool! I have two datasets with very different cell compositions (one dataset contains only T cells, and the other dataset has diverse cell types), and they benefited a lot from fastMNN integration.

Now I'd like to use the corrected data to understand how the cells from the 1st dataset communicate with malignant cells in the 2nd using CellPhoneDB/CellChat. However, both tools only accept normalized counts as input, and negative values are not allowed. Do you have advice on how to convert the corrected data to positive values?

Thank you very much!

**Comment by LTLA** [comment]
Hm. Not easily, the `fastMNN` approach doesn't generate "corrected counts", just corrected PCs. These can be converted into "corrected" expression values (see the `reconstructed` assay), but these are not guaranteed to be non-negative.

If non-negativity is the only problem here, you could generate non-negative values by taking the `exp()` of the reconstructed assay. However, this assumes that (i) those tools do not make any distributional assumptions about counts and (ii) your computer has enough memory to handle the non-sparse nature of the reconstructed assay.

**Comment by RoseString** [comment]
Thank you so much @LTLA ! If the values in the reconstructed assay are corrected PCs instead of corrected counts, does it mean that higher values do not suggest higher expression levels?

**Comment by LTLA** [comment]
The `reconstructed` assay contains the low-rank reconstruction of the expression matrix _from_ the corrected PCs, not the corrected PCs themselves. So it would be generally reasonable to interpret higher reconstructed values as higher expression values, though I would be cautious against reading too much into them. For example:

1. The correction process needs to merge two populations of the same cell type in different batches.
2. In one batch, gene X is silent in the cell type of interest, and in another batch, X is active in that same cell type. (Let's say because of different treatment conditions, or whatever).
3. In the merged dataset, X should have the same expression across batches, otherwise the batches won't be merged properly.
4. What should X's corrected expression values be? Should they be non-zero, in which case we might incorrectly think that X is expressed in both batches? Or should it be forced to zero, in which case we would think that X is silent in both batches?

Of course, corrected PCs can't be interpreted in this manner, so it doesn't matter for downstream steps like clustering.

**Comment by RoseString** [comment]
Thank you for your answer!!
