### ISSUE TITLE
how to do fastMNN compute.variances

### ISSUE THREAD

**Issue by mimi3421** [LTLA/batchelor#6]
Dear author,
I have seen that there was a _compute.variances_ parameter in the previous version of fastMNN in *scran* package. While I want to check out if there is any lost of biologically meaningful "batch effect" doing the fastMNN function, how can I achieve this purpose with current fastMNN missing the _compute.variances_ parameter? Thanks.

> In detail.
> I have three samples of tissues from the same donor and find that there is one specific type of cells show obviously larger "batch effect" than others. The cells can't be clustered together without batch removal while they can be merged in one cluster with fastMNN. I wonder if there is any biologically meaningful "batch effect" lost during fastMNN function. I think maybe the _compute.variances_ parameter can give me some tips about this.

**Comment by LTLA** [comment]
`fastMNN` will now always compute the variances. So if you follow the example in `?fastMNN`, you should be able to pull out the variances with `metadata(out)$merge.info$lost.var`.

**Comment by mimi3421** [comment]
Thanks a lot for your quick reply.
May I ask whether the _lost.var_ implies the total/average variance loss per batch? 
Is there any output of fastMNN which can infer the variance loss per gene (or per gene per batch)?

As I'm considering that there may be some meaningful gene expression changes nearly paralleling to the batch effect, I want to find some indexes like the coeffection of batch in linear regression (y~group+batch) that can provide some tips about the size of batch effect beneath each feature with fastMNN. I consider that after batch effect correction, the specific feature may undergo great but lower variance loss than random technical error.

**Comment by LTLA** [comment]
> May I ask whether the _lost.var_ implies the total/average variance loss per batch?

It computes the percentage of total variance lost in the low-dimensional space during the orthogonalization step of the `fastMNN` algorithm (see the Reference for more details). For each dimension, we compute the sum of squared differences from the mean across all cells, and then we add these values across dimensions; and we repeat this after orthogonalization.

Note that the variance lost only represents that due to the orthogonalization step, not the actual correction itself. It is difficult to interpret the latter because the variance in a batch might actually increase, e.g., if the cells are dragged outwards to align to a more spread-out reference batch. Or it might be lost but in a manner that does not imply an error in the correction.

> Is there any output of fastMNN which can infer the variance loss per gene (or per gene per batch)?

No, because there is no longer a concept of "gene" in the low-dimensional space.

> As I'm considering that there may be some meaningful gene expression changes nearly paralleling to the batch effect

Loss of biological differences is not uncommon. In fact, it is necessary for correction algorithms to work correctly. For example, if you want to align WT and KO cells, you will necessarily eliminate the difference in expression in the KO'd gene. This is a genuine biological difference but is uninteresting in the context of correction - otherwise you'd just end up with separate WT and KO clusters, and this would not be helpful if you wanted to annotate the common cell types.

The solution is to perform the DE analyses using the _original_ expression values, so as to capture the biology that was discarded during correction. I go into some detail about this [here](https://github.com/MarionILab/compareSingleCell).

**Comment by mimi3421** [comment]
Thank you for your suggestions and kind share of knowledge. 
The logics of "low-dimension" and "variance lost" you mentioned is very helpful to me. 
I'll have a look at your posts and try some DE or regression methods on the original expression.
